config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :transactions

  resources :wallets

  resources :vendors

  resources :gatekeepers

  resources :clients do
    member do
      post 'toggle'
      get  'verify'
      post 'verify' => 'clients#activate', as: :activate
      put  'verify' => 'clients#test_deposit', as: :test_deposit
    end
  end

  resources :bitpay_webhooks

  root "clients#index"

  post '/bitpay' => 'bitpay_webhooks#receive', as: :bitpay_notification

end

app/models/gatekeeper.rb
class Gatekeeper < ActiveRecord::Base
  has_many :users
  has_many :clients
end

app/controllers/gatekeepers_controller.rb
class GatekeepersController < ApplicationController
  before_action :set_gatekeeper, only: [:show, :edit, :update, :destroy]

  # GET /gatekeepers
  # GET /gatekeepers.json
  def index
    @gatekeepers = Gatekeeper.all
  end

  # GET /gatekeepers/1
  # GET /gatekeepers/1.json
  def show
  end

  # GET /gatekeepers/new
  def new
    @gatekeeper = Gatekeeper.new
  end

  # GET /gatekeepers/1/edit
  def edit
  end

  # POST /gatekeepers
  # POST /gatekeepers.json
  def create
    @gatekeeper = Gatekeeper.new(gatekeeper_params)

    respond_to do |format|
      if @gatekeeper.save
        format.html { redirect_to @gatekeeper, notice: 'Gatekeeper was successfully created.' }
        format.json { render :show, status: :created, location: @gatekeeper }
      else
        format.html { render :new }
        format.json { render json: @gatekeeper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gatekeepers/1
  # PATCH/PUT /gatekeepers/1.json
  def update
    respond_to do |format|
      if @gatekeeper.update(gatekeeper_params)
        format.html { redirect_to @gatekeeper, notice: 'Gatekeeper was successfully updated.' }
        format.json { render :show, status: :ok, location: @gatekeeper }
      else
        format.html { render :edit }
        format.json { render json: @gatekeeper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gatekeepers/1
  # DELETE /gatekeepers/1.json
  def destroy
    @gatekeeper.destroy
    respond_to do |format|
      format.html { redirect_to gatekeepers_url, notice: 'Gatekeeper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gatekeeper
      @gatekeeper = Gatekeeper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gatekeeper_params
      params.require(:gatekeeper).permit(:name)
    end
end

app/helpers/gatekeepers_helper.rb
module GatekeepersHelper
end

app/views/gatekeepers/_form.html.erb
<%= form_for @gatekeeper, :html => { :class => "form-horizontal gatekeeper" } do |f| %>

  <% if @gatekeeper.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@gatekeeper.errors.count, "error") %> prohibited this gatekeeper from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @gatekeeper.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                gatekeepers_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/gatekeepers/edit.html.erb
<%- model_class = Gatekeeper -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/gatekeepers/index.html.erb
<%- model_class = Gatekeeper -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @gatekeepers.each do |gatekeeper| %>
      <tr>
        <td><%= link_to gatekeeper.id, gatekeeper_path(gatekeeper) %></td>
        <td><%= gatekeeper.name %></td>
        <td><%=l gatekeeper.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_gatekeeper_path(gatekeeper), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      gatekeeper_path(gatekeeper),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_gatekeeper_path,
            :class => 'btn btn-primary' %>

app/views/gatekeepers/new.html.erb
<%- model_class = Gatekeeper -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/gatekeepers/show.html.erb
<%- model_class = Gatekeeper -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @gatekeeper.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              gatekeepers_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_gatekeeper_path(@gatekeeper), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              gatekeeper_path(@gatekeeper),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>