config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :transactions

  resources :wallets

  resources :vendors

  resources :gatekeepers

  resources :clients do
    member do
      post 'toggle'
      get  'verify'
      post 'verify' => 'clients#activate', as: :activate
      put  'verify' => 'clients#test_deposit', as: :test_deposit
    end
  end

  resources :bitpay_webhooks

  root "clients#index"

  post '/bitpay' => 'bitpay_webhooks#receive', as: :bitpay_notification

end

app/models/client.rb
class Client < ActiveRecord::Base
  require 'money-tree'
  require 'bip_mnemonic'
  require 'depositor'
  
  has_many :wallets, as: :transactor
  has_many :transactions, through: :wallets
  has_one :seed
  belongs_to :gatekeeper
  attr_encrypted :mnemonic, key: Rails.application.secrets.encryptor

  def self.active
    where(active: true)
  end

  def balance(currency = :btc)
    case currency
    when :usd
      usd_balance
    when :btc
      btc_balance
    end
  end

  def primary_wallets(n=1)
    n.times.map {|index| hd_master.node_for_path("m/44'/0'/0'/0/#{index}").to_address }
  end

  def change_wallets(n=1)
    n.times.map {|index| hd_master.node_for_path("m/44'/0'/0'/1/#{index}").to_address }
  end
  
  def primary_wallet(index=0)
    hd_master.node_for_path("m/44'/0'/0'/0/#{index}").to_address
  end

  def change_wallet(index=0)
    hd_master.node_for_path("m/44'/0'/0'/1/#{index}").to_address
  end

  def used_addresses
    self.wallets.map(&:address)
  end

  def activate
    update(active: true)
  end

  def toggle_activation
    active ? update(active: false) : update(active: true)
  end

  def test_deposit
    Depositor::Client.new(self).test_deposit
  end

  def daily_deposit
    Depositor::Client.new(self).deposit
  end

  def usd_balance
    (btc_balance * Global.first.btc_usd_spot_price).round(2)
  end

  def sent_txs
    transactions.where(client_was: "sender")
  end
  
  def text_message(text_msg)
    twilio = Twilio::REST::Client.new Rails.application.secrets.twilio_sid, Rails.application.secrets.twilio_token
    if !phone_number.nil?
      twilio.account.messages.create({
          :to => "+1" + phone_number,
          :from => Rails.application.secrets.twilio_number,
          :body => text_msg
      })
    end
  end

# Private 
  private

  def seed_text
    BipMnemonic.to_seed(mnemonic: mnemonic)
  end

  def hd_master
    MoneyTree::Master.new(seed_hex: seed_text)
  end

  def btc_balance
    wallets.map {|wallet| wallet.final_balance - wallet.unconfirmed_balance}.sum.to_f / (10 ** 8)
  end



end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy, :toggle, :verify, :activate, :test_deposit]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all.sort_by {|x| x.created_at }
    @spot_price = Global.first.btc_usd_spot_price
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @spot_price = Global.first.btc_usd_spot_price
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)
    seed = Seed.unused
    @client.attributes = {mnemonic: seed.seed}
    respond_to do |format|
      if @client.save
        seed.update(used: true, client_id: @client.id)
        format.html { redirect_to verify_client_path(@client), notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  def toggle
    @client.toggle_activation
    redirect_to :back
  end

  def verify
    @seed = @client.mnemonic
    @spot_price = Global.first.btc_usd_spot_price
  end

  def activate
    @client.activate
    redirect_to clients_path, notice: "#{@client.name.capitalize} is now active!"
  end

  def test_deposit
    @client.test_deposit
    redirect_to( :back, 
    notice: %Q[Test deposit sent to #{@client.name}, #{view_context.link_to("check wallet here", 'https://blockchain.info/address/' + @client.primary_wallet, target: "_blank", style: "text-decoration: underline; color: orange;")} and on their phone.],
    flash: { html_safe: true })
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :gatekeeper_id, :notes, :mnemonic)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for @client, :html => { :class => "form-horizontal client" } do |f| %>

  <% if @client.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @client.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :daily_usd_amount, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :daily_usd_amount, :class => 'form-control', disabled: true %>
    </div>
    <%=f.error_span(:daily_usd_amount) %>
  </div>
  <div class="form-group">
    <%= f.label :client_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :notes, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :notes, :class => 'form-control' %>
    </div>
    <%=f.error_span(:notes) %>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                clients_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/clients/edit.html.erb
<%- model_class = Client -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/clients/index.html.erb
<%- model_class = Client -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:balance) %></th>
      <th>Total Donations</th>
      <th>Semi-Daily Deposit</th>
      <th># TX's Sent</th>
      <th><%= model_class.human_attribute_name(:active) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @clients.each do |client| %>
      <tr <%= raw("class=hid hidden='hidden' style='background-color: #d89494;'") if client.hidden %> >
        <td><%= link_to client.name, client, class: "black-link" %></td>
        <td title="<%= client.balance %> BTC">$<%= price_round(client.balance * @spot_price) %></td>
        <td>$<%= price_round(client.total_donations) %></td>
        <td>$<%= price_round(client.daily_usd_amount) %></td>
        <td><%= client.sent_txs.count %></td>
        <td><%= client.active ? fa_icon("check-square", style: "color:green;padding-right:2px;", text: "Yes") : fa_icon("window-close", style: "color:red;padding-right:2px;", text: "No") %></td>
        <td><%= client.created_at.to_date %></td>
        <td>
          <%= link_to 'Activate/Deactivate',
                      toggle_client_path(client),
                      :method => :toggle_activation,
                      :data => { :confirm => 'Are you sure?' },
                      :class => 'btn btn-default btn-xs',
                      :disabled => client.hidden %>
          <% link_to 'Test Deposit', test_deposit_client_path(client), method: :put, :class => 'btn btn-default btn-xs'  %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_client_path,
            :class => 'btn btn-primary black-link' %>

app/views/clients/new.html.erb
<%- model_class = Client -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/clients/show.html.erb
<%- model_class = Client -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>




<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @client.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:daily_usd_amount) %>:</strong></dt>
  <dd>$<%= price_round(@client.daily_usd_amount) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:active) %>:</strong></dt>
  <dd><%= @client.active ? fa_icon("check-square", style: "color:green;padding-right:2px;", text: "Yes") : fa_icon("window-close", style: "color:red;padding-right:2px;", text: "No")  %></dd>
  <dt><strong>Last Known Balance:</strong></dt>
  <dd>$<%= price_round(@client.balance * @spot_price) %></dd>
  <dt><strong>Total Donations:</strong></dt>
  <dd>$<%= price_round(@client.total_donations) %></dd>
  <dt><strong>Deposit Address:</strong></dt>
  <dd><%= link_to @client.primary_wallet, address_link(@client.primary_wallet) %></dd>
  <br>
  <a style="border: 2px solid grey" class="btn btn-success btn-xs" onclick="reveal('seed')">Reveal Wallet Seed:</a>
  <br>
  <div style="padding-top: 3px"><p style="font-size: medium;" class="myHiddenText" id="seed"><%= @client.mnemonic %></p></div>
</dl>

<%= link_to 'Test Deposit', test_deposit_client_path, method: :put, :class => 'btn btn-warning btn-xs', style: "color: white", :disabled => @client.hidden  %>
<br>
<%= link_to 'Activate/Deactivate', toggle_client_path, :method => :toggle_activation, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-xs btn-danger', style: "color: white; margin-top: 4px", :disabled => @client.hidden %>
<br><br>
<%= link_to t('.back', :default => t("helpers.links.back")),
              clients_path, :class => 'btn btn-default btn-xs'  %>
<br><br>
<div class="client-tx-list">
  <div><h3>Transactions</h3></div>
  <table>
    <thead>
      <th>Date</th>
      <th>Amount</th>
      <th>TxId</th>
      <th>Tx/Rx</th>
      <th>Valid?</th>
      <th>Bitpay</th>
      <th>Info</th>
    </thead>
    <tbody>
      <% @client.transactions.sort_by(&:received).reverse.each do |tx| %>
        <tr>
          <td ><%= tx.received.to_s[0..15] %></td>
          <td >$<%= price_round(tx.sent_usd_price) %></td>
          <td><%= link_to short(tx.txid), tx_link(tx.txid), class: "orange-link" %></td>
          <td><%= tx.client_was.capitalize %></td>
          <td><%= tx.validated ? fa_icon("check-square", style: "color:green;padding-right:2px;", text: "Yes") : fa_icon("window-close", style: "color:red;padding-right:2px;", text: "No")  %></td>
          <td><%= tx.bitpay_tx ? ( link_to tx.bitpay_tx.bitpay_id[0..4] + "...", tx.bitpay_tx.url ) : "N/A" %></td>
          <td><%= link_to "Info", tx %></td>
        <tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/clients/verify.html.erb
<%- model_class = Client -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @client.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:daily_usd_amount) %>:</strong></dt>
  <dd>$<%= price_round(@client.daily_usd_amount) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:active) %>:</strong></dt>
  <dd><%= @client.active ? fa_icon("check-square", style: "color:green;padding-right:2px;", text: "Yes") : fa_icon("window-close", style: "color:red;padding-right:2px;", text: "No")  %></dd>
  <br>
  <dt>Wallet Seed:</strong></dt>
  <dd style="font-size: large"><%= @client.mnemonic %></dd>
</dl>


<% if @client.test_deposit_made %>
  <%= link_to 'Activate', activate_client_path(@client), method: :post, :class => 'btn btn-success', :data => { :confirm => 'Are you sure? Refresh the client\'s Jaxx wallet to confirm test transaction.' } %>
<% else %>
  <%= link_to 'Test Deposit', test_deposit_client_path, method: :put, :class => 'btn btn-warning'  %>
<% end %>