config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :transactions

  resources :wallets

  resources :vendors

  resources :gatekeepers

  resources :clients do
    member do
      post 'toggle'
      get  'verify'
      post 'verify' => 'clients#activate', as: :activate
      put  'verify' => 'clients#test_deposit', as: :test_deposit
    end
  end

  resources :bitpay_webhooks

  root "clients#index"

  post '/bitpay' => 'bitpay_webhooks#receive', as: :bitpay_notification

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  has_many :wallets, as: :transactor
  attr_encrypted :bitpay_pem, key: Rails.application.secrets.encryptor

  def self.address_list
    all.map(&:address_list).flatten
  end

  def address_list
    wallets.map(&:address)
  end

end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :edit, :update, :destroy]

  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = Vendor.all
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: 'Vendor was successfully created.' }
        format.json { render :show, status: :created, location: @vendor }
      else
        format.html { render :new }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1
  # PATCH/PUT /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to @vendor, notice: 'Vendor was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor.destroy
    respond_to do |format|
      format.html { redirect_to vendors_url, notice: 'Vendor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendor_params
      params.require(:vendor).permit(:name)
    end
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.html.erb
<%= form_for @vendor, :html => { :class => "form-horizontal vendor" } do |f| %>

  <% if @vendor.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@vendor.errors.count, "error") %> prohibited this vendor from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @vendor.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :encrypted_bitpay_pem, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :encrypted_bitpay_pem, :class => 'form-control' %>
    </div>
    <%=f.error_span(:encrypted_bitpay_pem) %>
  </div>
  <div class="form-group">
    <%= f.label :encrypted_bitpay_pem_iv, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :encrypted_bitpay_pem_iv, :class => 'form-control' %>
    </div>
    <%=f.error_span(:encrypted_bitpay_pem_iv) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                vendors_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/vendors/edit.html.erb
<%- model_class = Vendor -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/vendors/index.html.erb
<%- model_class = Vendor -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:encrypted_bitpay_pem) %></th>
      <th><%= model_class.human_attribute_name(:encrypted_bitpay_pem_iv) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @vendors.each do |vendor| %>
      <tr>
        <td><%= link_to vendor.id, vendor_path(vendor) %></td>
        <td><%= vendor.name %></td>
        <td><%= vendor.encrypted_bitpay_pem %></td>
        <td><%= vendor.encrypted_bitpay_pem_iv %></td>
        <td><%=l vendor.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_vendor_path(vendor), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      vendor_path(vendor),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_vendor_path,
            :class => 'btn btn-primary' %>

app/views/vendors/new.html.erb
<%- model_class = Vendor -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/vendors/show.html.erb
<%- model_class = Vendor -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @vendor.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:encrypted_bitpay_pem) %>:</strong></dt>
  <dd><%= @vendor.encrypted_bitpay_pem %></dd>
  <dt><strong><%= model_class.human_attribute_name(:encrypted_bitpay_pem_iv) %>:</strong></dt>
  <dd><%= @vendor.encrypted_bitpay_pem_iv %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              vendors_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_vendor_path(@vendor), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              vendor_path(@vendor),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>