config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :transactions

  resources :wallets

  resources :vendors

  resources :gatekeepers

  resources :clients do
    member do
      post 'toggle'
      get  'verify'
      post 'verify' => 'clients#activate', as: :activate
      put  'verify' => 'clients#test_deposit', as: :test_deposit
    end
  end

  resources :bitpay_webhooks

  root "clients#index"

  post '/bitpay' => 'bitpay_webhooks#receive', as: :bitpay_notification

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "DGP" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand " href="/"><b>DGP</b></a>
        <% if user_signed_in? %>
        <span class="header-data">
          <b>Total Donations:</b> <span>$<%= price_round(Client.all.map(&:total_donations).sum) %></span>
          <b>Client Payed Fees:</b> <span>$<%= price_round(Transaction.where(client_was: "sender").map(&:fees_usd_price).sum) %></span>
          <br><b>Active Clients:</b> <span><%= Client.active.count %></span>
          <b style="padding-left: 55px;">Total Fees:</b> <span>$<%= price_round(Transaction.all.map(&:fees_usd_price).sum) %></span>
        </span>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav" style="float: right;">
          <li style="font-size: small;color: green;"><%= link_to "BTC/USD $" + price_round(DGP::MarketData.usd_btc_spot_price), "https://www.coinbase.com/charts", style: "font-size: small;color: green;" %></li>
            <li><%= link_to "Clients", clients_path %></li>
            <li><% link_to "Vendors", vendors_path  %></li>
            <li><% link_to "Wallets", wallets_path  %></li>
            <li><%= link_to "Transactions", transactions_path  %></li>
            <li><%= link_to "Bitpay Txs", bitpay_webhooks_path  %></li>
            <li><%= link_to "Wallets", wallets_path %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>

          </ul>
        </div>
        <% end %>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-sm-12">
        <% if user_signed_in? %>
          <%= bootstrap_flash %>
        <% end %>
          <%= yield %>
        </div>
<!--         <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div>
        </div> -->
      </div><!--/row-->

      <footer>
        <p><span id="unHide">&copy;</span> Distributed Giving Project 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
  <script type="text/javascript">
    $('#unHide').on('click', function () {
      console.debug("Test Clients now showing!");
      $('.hid').show();
    });
</script>

</html>